buildscript {
    ext.kotlin_version = "1.9.22"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.4.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.3.15'
        // END: FlutterFire Configuration
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    def configureProject = { p ->
        if (p.hasProperty('android')) {
            p.android {
                compileOptions {
                    sourceCompatibility JavaVersion.VERSION_17
                    targetCompatibility JavaVersion.VERSION_17
                }
                if (p.plugins.hasPlugin('kotlin-android')) {
                    p.android.kotlinOptions {
                        jvmTarget = '17'
                    }
                }
                if (namespace == null) {
                    def manifestPath = file("${p.projectDir}/src/main/AndroidManifest.xml")
                    if (manifestPath.exists()) {
                        def matcher = manifestPath.text =~ /package="([^"]+)"/
                        if (matcher.find()) {
                            namespace = matcher[0][1]
                        } else if (p.group != null && !p.group.toString().isEmpty()) {
                            namespace = p.group.toString()
                        }
                    } else if (p.group != null && !p.group.toString().isEmpty()) {
                        namespace = p.group.toString()
                    }
                }
            }
        }
    }

    if (project.state.executed) {
        configureProject(project)
    } else {
        project.afterEvaluate { configureProject(project) }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
